// Generated by CoffeeScript 1.4.0

/*
 * @package		Home
 * @category	modules
 * @author		Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright	Copyright (c) 2013, Nazar Mokrynskyi
 * @license		MIT License, see license.txt
*/


(function() {

  $(function() {
    var container;
    if (!$('#driver-map').length) {
      return;
    }
    container = $('.home-page-filter');
    container.find('input[name=date]').pickmeup({
      format: 'd.m.Y',
      onChange: function(formated) {
        return container.find('[name=date]').val(formated).pickmeup('hide');
      }
    });
    container.find('[name=time]').next().find('a').click(function() {
      return container.find('[name=time]').val($(this).text());
    });
    return ymaps.ready(function() {
      var map;
      map = new ymaps.Map('driver-map', {
        center: [50.4505, 30.523],
        zoom: 13,
        controls: ['geolocationControl', 'fullscreenControl', 'typeSelector', 'zoomControl']
      });
      if (navigator.geolocation) {
        return navigator.geolocation.getCurrentPosition(function(position) {
          return map.panTo([position.coords.latitude, position.coords.longitude]);
        }, function() {}, {
          enableHighAccuracy: true,
          timeout: 30 * 60 * 1000
        });
      }
      /*placemark	= new ymaps.Placemark(myMap.getCenter(), {
      			balloonContentBody: [
      				'<address>',
      				'<strong>Офис Яндекса в Москве</strong>',
      				'<br/>',
      				'Адрес: 119021, Москва, ул. Льва Толстого, 16',
      				'<br/>',
      				'Подробнее: <a href="http://company.yandex.ru/">http://company.yandex.ru/<a>',
      				'</address>'
      			].join('')
      		}, {
      			preset: 'islands#redDotIcon'
      		})
      		map.geoObjects.add(myPlacemark)
      */

    });
  });

}).call(this);
