// Generated by CoffeeScript 1.4.0

/*
 * @package		Home
 * @category	modules
 * @author		Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright	Copyright (c) 2013, Nazar Mokrynskyi
 * @license		MIT License, see license.txt
*/


(function() {

  $(function() {
    return $('.home-page-sign-in a').click(function() {
      var $this, provider;
      $this = $(this);
      provider = $this.hasClass('fb') ? 'Facebook' : 'Vkontakte';
      return $.ajax({
        url: 'api/Home/i_am_driver',
        data: {
          driver: $this.hasClass('driver') ? 1 : 0
        },
        success: function() {
          return location.href = 'HybridAuth/' + provider;
        },
        error: function(xhr) {
          if (xhr.responseText) {
            return alert(cs.json_decode(xhr.responseText).error_description);
          } else {
            return alert(L.auth_connection_error);
          }
        }
      });
    });
  });

}).call(this);
