// Generated by CoffeeScript 1.4.0

/*
 * @package		Home
 * @category	modules
 * @author		Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright	Copyright (c) 2013, Nazar Mokrynskyi
 * @license		MIT License, see license.txt
*/


(function() {

  $(function() {
    if (!$('#user-map').length) {
      return;
    }
    return ymaps.ready(function() {
      var map;
      map = new ymaps.Map('user-map', {
        center: [50.4505, 30.523],
        zoom: 12,
        controls: ['zoomControl']
      });
      if (navigator.geolocation) {
        return navigator.geolocation.getCurrentPosition(function(position) {
          return map.panTo([position.coords.latitude, position.coords.longitude]);
        }, function() {}, {
          enableHighAccuracy: true,
          timeout: 120 * 1000
        });
      }
      /*placemark	= new ymaps.Placemark(myMap.getCenter(), {
      			balloonContentBody: [
      				'<address>',
      				'<strong>Офис Яндекса в Москве</strong>',
      				'<br/>',
      				'Адрес: 119021, Москва, ул. Льва Толстого, 16',
      				'<br/>',
      				'Подробнее: <a href="http://company.yandex.ru/">http://company.yandex.ru/<a>',
      				'</address>'
      			].join('')
      		}, {
      			preset: 'islands#redDotIcon'
      		})
      		map.geoObjects.add(myPlacemark)
      */

    });
  });

}).call(this);
