// Generated by CoffeeScript 1.4.0

/*
 * @package		Home
 * @category	modules
 * @author		Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright	Copyright (c) 2013, Nazar Mokrynskyi
 * @license		MIT License, see license.txt
*/


(function() {

  $(function() {
    var container, coordinates;
    if (!$('#user-map').length) {
      return;
    }
    container = $('.home-page-add-goods');
    coordinates = container.find('[name=coordinates]');
    return ymaps.ready(function() {
      var icon_number, map, me;
      map = new ymaps.Map('user-map', {
        center: [50.4505, 30.523],
        zoom: 13,
        controls: ['zoomControl']
      });
      icon_number = Math.round(Math.random() * 11);
      me = new ymaps.Placemark([50.45056507697532, 30.523316500663444], {}, {
        draggable: true,
        iconLayout: 'default#image',
        iconImageHref: '/components/modules/Home/includes/img/map-icons.png',
        iconImageSize: [60, 58],
        iconImageOffset: [-24, -58],
        iconImageClipRect: [[60 * icon_number, 0], [60 * (icon_number + 1), 58]]
      });
      map.geoObjects.add(me);
      me.events.add('geometrychange', function(e) {
        var coords;
        coords = cs.json_encode(e.get('originalEvent').originalEvent.newPosition);
        return coordinates.val(coords);
      });
      if (navigator.geolocation) {
        return navigator.geolocation.getCurrentPosition(function(position) {
          map.panTo([position.coords.latitude, position.coords.longitude]);
          return me.geometry.setCoordinates(map.getCenter());
        }, function() {}, {
          enableHighAccuracy: true,
          timeout: 120 * 1000
        });
      }
      /*placemark	= new ymaps.Placemark(myMap.getCenter(), {
      			balloonContentBody: [
      				'<address>',
      				'<strong>Офис Яндекса в Москве</strong>',
      				'<br/>',
      				'Адрес: 119021, Москва, ул. Льва Толстого, 16',
      				'<br/>',
      				'Подробнее: <a href="http://company.yandex.ru/">http://company.yandex.ru/<a>',
      				'</address>'
      			].join('')
      		}, {
      			preset: 'islands#redDotIcon'
      		})
      		map.geoObjects.add(myPlacemark)
      */

    });
  });

}).call(this);
