// Generated by CoffeeScript 1.4.0

/*
 * @package		Home
 * @category	modules
 * @author		Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright	Copyright (c) 2013-2014, Nazar Mokrynskyi
 * @license		MIT License, see license.txt
*/


(function() {

  $(function() {
    var add_good_map, container, coordinates;
    add_good_map = $('#add-good-map');
    if (add_good_map.length) {
      container = $('.cs-home-page-add-goods');
      container.find('[name=date]').pickmeup({
        format: 'd.m.Y',
        mode: 'range',
        change: function(formated) {
          return container.find('[name=date]').val(formated.join(' - '));
        }
      });
      container.find('[name=time]').next().find('a').click(function() {
        return container.find('[name=time]').val($(this).text());
      });
      coordinates = container.find('[name=coordinates]');
      ymaps.ready(function() {
        var address_timeout, icon_number, map, me;
        map = new ymaps.Map('add-good-map', {
          center: cs.json_decode(coordinates.val()),
          zoom: 13,
          controls: ['zoomControl']
        });
        add_good_map.data('map', map);
        icon_number = Math.round(Math.random() * 11);
        me = new ymaps.Placemark(cs.json_decode(coordinates.val()), {}, {
          draggable: true,
          iconLayout: 'default#image',
          iconImageHref: '/components/modules/Home/includes/img/map-icons.png',
          iconImageSize: [60, 58],
          iconImageOffset: [-24, -58],
          iconImageClipRect: [[60 * icon_number, 0], [60 * (icon_number + 1), 58]]
        });
        map.geoObjects.add(me);
        me.events.add('geometrychange', function(e) {
          var coords;
          coords = cs.json_encode(e.get('originalEvent').originalEvent.newCoordinates);
          return coordinates.val(coords);
        });
        if (navigator.geolocation) {
          if (!container.find('[name=address]').val()) {
            navigator.geolocation.getCurrentPosition(function(position) {
              var coords;
              coords = [position.coords.latitude, position.coords.longitude];
              map.panTo(coords);
              return me.geometry.setCoordinates(coords);
            }, function() {}, {
              enableHighAccuracy: true,
              timeout: 120 * 1000
            });
          }
          address_timeout = 0;
          return container.find('[name=address]').on('keyup change', function() {
            if ($(this).val().length < 4) {
              return;
            }
            clearTimeout(address_timeout);
            return address_timeout = setTimeout((function() {
              return ymaps.geocode(container.find('[name=address]').val()).then(function(res) {
                var coords;
                coords = res.geoObjects.get(0).geometry.getCoordinates();
                map.panTo(coords, {
                  fly: true,
                  checkZoomRange: true
                });
                me.geometry.setCoordinates(coords);
                return coordinates.val(cs.json_encode(coords));
              });
            }), 300);
          }).keyup();
        }
      });
      $('.cs-home-i-have-a-car').click(function() {
        return $.ajax({
          url: 'api/Home/i_have_a_car',
          type: 'put',
          success: function() {
            alert('Дякуємо!) Після перевірки вашого облікового запису вам буде надано персональний код водія та доступ до контактів волонтерів з речами');
            return location.reload();
          }
        });
      });
      container.submit(function() {
        $.ajax({
          url: 'api/Home/goods',
          type: 'post',
          data: {
            name: container.find('[name=name]').val(),
            phone: container.find('[name=phone]').val(),
            address: container.find('[name=address]').val(),
            coordinates: container.find('[name=coordinates]').val(),
            date: container.find('[name=date]').val(),
            time: container.find('[name=time]').val(),
            comment: container.find('[name=comment]').val()
          },
          success: function() {
            return $("<div>\n	<div class=\"uk-form\" style=\"width: 700px;\">\n		<h2 class=\"cs-center\">Дякуємо за розміщену інформацію про наявні речі!</h2>\n		<p class=\"cs-center\">Вільний водій зв’яжеться з вами за першої нагоди.</p>\n		<p>Коли віддаватимете речі - спитайте про код, який має кожен водій. Цей код використовується задля контролю чесності та надійності водіїв.</p>\n		<p>В розділі \"Мої речі\" нижче ви можете підтвердити передачу речей водію, ввівши його код.</p>\n	</div>\n</div>").appendTo('body').cs().modal('show').on('uk.modal.hide', function() {
              $(window).scrollTop(0);
              location.reload();
              return $(this).remove();
            });
          }
        });
        return false;
      });
      $('.cs-home-page-add-goods-button').click(function() {
        var $this;
        $('.cs-home-page-add-goods').slideToggle(function() {
          add_good_map = $('#add-good-map').data('map');
          return add_good_map.setBounds(add_good_map.getBounds());
        });
        $this = $(this);
        if ($this.find('.uk-icon-caret-down').length) {
          return $this.find('.uk-icon-caret-down').removeClass('uk-icon-caret-down').addClass('uk-icon-caret-up');
        } else {
          return $this.find('.uk-icon-caret-up').removeClass('uk-icon-caret-up').addClass('uk-icon-caret-down');
        }
      });
      return $('.cs-home-page-my-goods-list').on('click', '.cs-home-page-delete-good', function() {}).on('click', '.cs-home-page-confirm-good', function() {
        var id, modal;
        id = $(this).data('id');
        modal = $.cs.simple_modal("<p>Введіть код, який ви отримали від водія, щоб ми знали, хто відвозить ваші речі</p>\n<input placeholder=\"Код водія\" autofocus>\n<button class=\"uk-button\">Готово</button>", true, 500);
        return modal.find('button').click(function() {
          return $.ajax({
            url: "api/Home/goods/" + id + "/confirm",
            type: 'post',
            data: {
              confirmation_code: modal.find('input').val()
            },
            success: function() {
              alert('Дякуємо, що творите добрі справи!');
              return location.reload();
            }
          });
        });
      });
    }
  });

}).call(this);
