// Generated by CoffeeScript 1.4.0

/**
 * @package		CherryTea
 * @category	themes
 * @author		Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright	Copyright (c) 2013-2014, Nazar Mokrynskyi
 * @license		MIT License, see license.txt
*/


(function() {



}).call(this);
